/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.4 at Wed Aug 23 15:25:39 2017. */

#include "addsec_cti.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const uint32_t ObservationData_dataType_default = 0u;
const uint32_t Sighting_sightingType_default = 0u;
const uint32_t Sighting_confidence_default = 0u;
const uint32_t Report_systemType_default = 0u;


const pb_field_t ObservationData_fields[4] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, ObservationData, dataType, dataType, &ObservationData_dataType_default),
    PB_FIELD(  2, BYTES   , OPTIONAL, CALLBACK, OTHER, ObservationData, data, dataType, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, ObservationData, num, data, 0),
    PB_LAST_FIELD
};

const pb_field_t Sighting_fields[8] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, Sighting, sightingType, sightingType, &Sighting_sightingType_default),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, Sighting, timestamp, sightingType, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, Sighting, confidence, timestamp, &Sighting_confidence_default),
    PB_FIELD(  5, MESSAGE , REPEATED, CALLBACK, OTHER, Sighting, datas, confidence, &ObservationData_fields),
    PB_FIELD(  6, UINT32  , OPTIONAL, STATIC  , OTHER, Sighting, testId, datas, 0),
    PB_FIELD(  7, UINT32  , OPTIONAL, STATIC  , OTHER, Sighting, testSubId, testId, 0),
    PB_FIELD(  8, UINT32  , OPTIONAL, STATIC  , OTHER, Sighting, timeDelta, testSubId, 0),
    PB_LAST_FIELD
};

const pb_field_t Report_fields[11] = {
    PB_FIELD(  1, BYTES   , OPTIONAL, STATIC  , FIRST, Report, organizationId, organizationId, 0),
    PB_FIELD(  2, BYTES   , OPTIONAL, STATIC  , OTHER, Report, systemId, organizationId, 0),
    PB_FIELD(  3, BYTES   , OPTIONAL, CALLBACK, OTHER, Report, systemIdSecondary, systemId, 0),
    PB_FIELD(  4, UINT32  , OPTIONAL, STATIC  , OTHER, Report, systemType, systemIdSecondary, &Report_systemType_default),
    PB_FIELD(  5, BYTES   , OPTIONAL, STATIC  , OTHER, Report, applicationId, systemType, 0),
    PB_FIELD(  6, BYTES   , OPTIONAL, STATIC  , OTHER, Report, userId, applicationId, 0),
    PB_FIELD(  7, BYTES   , OPTIONAL, CALLBACK, OTHER, Report, userIdSecondary, userId, 0),
    PB_FIELD(  8, MESSAGE , REPEATED, CALLBACK, OTHER, Report, sightings, userIdSecondary, &Sighting_fields),
    PB_FIELD(  9, UINT32  , OPTIONAL, STATIC  , OTHER, Report, timeBase, sightings, 0),
    PB_FIELD( 10, BYTES   , OPTIONAL, CALLBACK, OTHER, Report, version, timeBase, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Sighting, datas) < 65536 && pb_membersize(Report, sightings) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_ObservationData_Sighting_Report)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Sighting, datas) < 256 && pb_membersize(Report, sightings) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_ObservationData_Sighting_Report)
#endif


