
LIBNOM := libas_common
TARGET := darwin
ARCH ?= host

# OS:
#DEFS := -DASCTI_SYSTEM_TYPE=1  -DNDEBUG=1 

# Sensor/IoT:
DEFS := -DASCTI_SYSTEM_TYPE=11  -DNDEBUG=1 -DCONSTRAINED_DEVICE

SHAREDLIBEXT := .dylib

BUILD_DIR = build/

include ../common/top.mk
